
spring:
  application:
    name: fraud

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: postgres
    password: Eneye@chinu1
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

server:
  port: 8078