
spring:
  application:
    name: fraud

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud

    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create-drop #update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8078